### ISSUE TITLE
link-citations don't work on pdf output

### ISSUE THREAD

**Issue by mathoory** [christopherkenny/cambridge-medium#3]
I'm using `link-citations: true` to have hyperlinks from in-body citations to the references at the end of the document (as instructed here: https://github.com/quarto-dev/quarto-cli/issues/3197).
Would love to hear your thoughts about this one, as this is important to me when writing an article to be able to jump back and forth to actual references part (esp. when using zotero that gives somekind of preview on hyperlinks). 
Thanks!

This seems to work with the default quarto setup:

```
---
title: Cambridge-Medium Template
format:
  pdf:
    keep-tex: true
    journal: medium
    year: 2023
    volume: NA
    link-citations: true
..... (rest unchanged from the template) ...
---
```
![default](https://github.com/user-attachments/assets/03bcce6c-d884-4d0b-b101-2f881c3938e5)

It doesn't work with the cambridge-medium template:
![cambridge-medium](https://github.com/user-attachments/assets/0ba8fcdb-a67d-4fe7-bba7-f169ace6ac0f)
```
---
title: Cambridge-Medium Template
format:
  cambridge-medium-pdf:
    keep-tex: true
    journal: medium
    year: 2023
    volume: NA
    link-citations: true
..... (rest unchanged from the template) ...
---
```

Setup:
Windows 11
RStudio 2024.09.1 Build 394
Quarto 1.5.57
XeTeX, Version 3.141592653-2.6-0.999994 (MiKTeX 22.3) (preloaded format=xelatex.fmt)
 restricted \write18 enabled.
